Adicionando Playlist Service
Lucas-Anseloni/projetct-myMusic-toTal pull request #16
Opened 2022-07-20 14:16 UTC by francielydb

2022-07-20 22:04 UTC, viniciussouza-cit requested changes

2022-07-20 22:04 UTC, viniciussouza-cit commented on MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/PlaylistServiceImpTest.java
> +        Playlist p1 = new Playlist("93f7da42-d9e5-4e50-a789-b4f406897dd7", new ArrayList<>());
Não encontrei a entity `Playlist` na sua branch, faltou comitar ou será que faltou um merge aqui com a branch `main`?

Outra dúvida, o projeto está compilando corretamente?

2022-07-21 11:08 UTC, francielydb commented on MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/PlaylistServiceImp.java
> +        playlistRepository.save(playlist);
Fiquei um pouco confusa sobre como trabalhar diretamente com esse PlaylistMusicas.. 
E ele realmente não estava salvando no banco. Fiz uma modificação logo antes de enviar e esqueci de adicionar a música que vem do request no list da playlist. Corrigido e testado, agora está salvando de novo.

2022-07-21 11:08 UTC, francielydb commented on MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/PlaylistServiceImpTest.java
> +        Playlist p1 = new Playlist("93f7da42-d9e5-4e50-a789-b4f406897dd7", new ArrayList<>());
Eu tinha feito essa task antes da entity Playlist e do repository terem sido aprovados e enviados pra main, daí eu só copiei as classes que o pessoal tinha feito pra conseguir testar e na hora de comitar ignorei os arquivos pra não dar conflito. Com essas classes que eu não commitei está compilando sim.

2022-07-21 11:08 UTC, francielydb commented on MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/PlaylistServiceImpTest.java
> +        if (!musicas.contains(pR1.getData())) {
Foi erro meu, já fiz a correção!

2022-07-21 14:10 UTC, viniciussouza-cit commented on MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/PlaylistServiceImpTest.java
> +        Playlist p1 = new Playlist("93f7da42-d9e5-4e50-a789-b4f406897dd7", new ArrayList<>());
A, então ok. Talvez faça sentido realizar o merge back o quanto antes, até mesmo antes de commitar, pois se tivéssemos uma CI compilando, teríamos uma falha.

2022-07-21 17:30 UTC, viniciussouza-cit commented on MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/request/PlaylistRequest.java
> +    Musica data;
Seria interessante a gente não utilizar uma entidade de domínio diretamente na controller. Talvez ter uma dto no meio para receber os dados.

2022-07-21 19:13 UTC, francielydb commented on MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/request/PlaylistRequest.java
> +    Musica data;
Adicionamos o model MusicaDTO para fazer essa ponte entre o request e o controller.

2022-07-21 19:14 UTC, francielydb commented on MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/PlaylistServiceImp.java
> +        playlistRepository.save(playlist);
Adicionamos a entidade de PlaylistMusica!

2022-07-21 19:24 UTC, viniciussouza-cit requested changes

2022-07-21 19:24 UTC, viniciussouza-cit commented on MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/model/MusicaDTO.java
> +    private Artista artista;
Aqui seria legal criar um ArtistaDTO também

2022-07-21 19:24 UTC, viniciussouza-cit commented on MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/repository/PlaylistMusicaRepository.java
> +    List<PlaylistMusica> findByPlaylistIdAndMusicaId(String playlistMusicas, String musicaId);
Aqui poderia retornar apenas um item né, não precisaria retornar uma lista, pois seria tipo um `Get By Id`.

2022-07-21 19:36 UTC, francielydb commented on MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/model/MusicaDTO.java
> +    private Artista artista;
Adicionado! :)

2022-07-21 19:36 UTC, francielydb commented on MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/repository/PlaylistMusicaRepository.java
> +    List<PlaylistMusica> findByPlaylistIdAndMusicaId(String playlistMusicas, String musicaId);
Corrigido.

2022-07-21 19:53 UTC, viniciussouza-cit approved these changes
Top pessoal, ficou muito bom. Congrats 🎉

2022-07-21 19:54 UTC, merged